name: Build Samsung A06 Kernel (KSU Next + SUSFS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget curl build-essential bc bison flex             libssl-dev libelf-dev ccache unzip python3 clang llvm lld dos2unix

      - name: Download Kernel Source (Release auto-detect)
        run: |
          echo "⬇️ Tải kernel source tự động từ release V1"
          ASSET_URL=$(curl -s https://api.github.com/repos/huyzilo77-bot/Bufffkerrnela065g/releases/tags/V1             | grep "browser_download_url"             | head -n 1             | cut -d '"' -f 4)

          if [ -z "$ASSET_URL" ]; then
            echo "❌ Không tìm thấy asset trong release!"
            exit 1
          fi

          wget -nv -O kernel.tar "$ASSET_URL"
          mkdir -p kernel-5.15
          tar -xf kernel.tar -C kernel-5.15 --strip-components=1
          echo "✅ Giải nén thành công"

      - name: Clone SUSFS
        run: |
          git clone -b gki-android13-5.15 https://gitlab.com/simonpunk/susfs4ksu.git susfs

      - name: Apply SUSFS patches
        run: |
          cd kernel-5.15
          patch -p1 --forward < ../susfs/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch || true
          cp -r ../susfs/kernel_patches/fs/* fs/ || true
          cp -r ../susfs/kernel_patches/include/linux/* include/linux/ || true

      - name: Collect .rej files
        if: always()
        run: |
          mkdir -p rej_artifacts
          find kernel-5.15 -type f -name "*.rej" -print > rej_artifacts/rej-list.txt || true
          if [ -s rej_artifacts/rej-list.txt ]; then
            tar -czf rej_artifacts/rej-files.tar.gz -T rej_artifacts/rej-list.txt
            echo "HAS_REJ=1" >> $GITHUB_ENV
          else
            echo "HAS_REJ=0" >> $GITHUB_ENV
            echo "⚠️ Không có file .rej"
          fi

      - name: Upload REJ artifact
        if: env.HAS_REJ == '1'
        uses: actions/upload-artifact@v4
        with:
          name: SUSFS-REJ-files
          path: rej_artifacts/rej-files.tar.gz

      - name: Upload REJ to Release
        if: env.HAS_REJ == '1'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: rej-${{ github.run_id }}
          name: "REJ dump ${{ github.run_id }}"
          files: rej_artifacts/rej-files.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
