name: Build Samsung A06 GKI Kernel (KSU + SUSFS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean
          df -h

      - name: Install deps & toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl unzip bc build-essential ccache \
            flex bison libssl-dev libncurses5-dev python3 clang lld

       - name: 📦 Install toolchains (Clang + GCC)
        run: |
          mkdir -p ~/toolchains
          cd ~/toolchains
          # Download Android prebuilt clang
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r450784d.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz
          # Export paths
          echo "PATH=$HOME/toolchains/bin:$PATH" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
        
      - name: Setup ccache
        run: |
          export USE_CCACHE=1
          ccache -M 10G
          ccache -z

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: 📥 Download Samsung A06 Kernel Source
        run: |
          mkdir -p kernel-src
          cd kernel-src
          wget -q https://github.com/huyzilo77-bot/Bufffkerrnela065g/releases/download/V1/A066B-5G.zip -O kernel.zip
          unzip -q kernel.zip
          tar -xvf Kernel.tar.gz
          ls -la

      - name: 🌱 Detect Kernel Dir
        run: |
          cd kernel-src
          if [ -d "kernel-5.15" ]; then
            echo "KERNEL_DIR=kernel-5.15" >> $GITHUB_ENV
          elif [ -d "kernel" ]; then
            echo "KERNEL_DIR=kernel" >> $GITHUB_ENV
          else
            echo "❌ Không tìm thấy thư mục kernel!"
            exit 1
          fi

      - name: 🔧 Fix permissions for build scripts
        run: |
          cd kernel-src/$KERNEL_DIR
          # Cấp quyền thực thi cho tất cả script .sh và build.config*
          find . -type f -name "*.sh" -exec chmod +x {} \;
          find . -type f -name "build.config*" -exec chmod +x {} \;
          chmod -R +x . || true

      - name: 🌱 Clone KernelSU-Next & SUSFS & AnyKernel3
        run: |
          git clone --depth=1 https://github.com/KernelSU-Next/KernelSU-Next.git KernelSU-Next
          git clone --depth=1 https://github.com/sidex15/susfs4ksu-module.git susfs
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git AnyKernel3

      - name: 🌱 Apply KernelSU
        run: |
          cd kernel-src/$KERNEL_DIR
          bash ../../KernelSU-Next/kernel/setup.sh || true

      - name: 🌱 Apply SUSFS
        run: |
          cd kernel-src/$KERNEL_DIR
          patch -p1 < ../../susfs/susfs.patch || true

      - name: ⚡ Force enable KSU & SUSFS via build.config
        run: |
          CONFIG_FILE="kernel-src/$KERNEL_DIR/build.config.mtk.aarch64"
          echo 'POST_DEFCONFIG_CMDS="
            echo CONFIG_KSU=y >> $OUT_DIR/.config;
            echo CONFIG_SUSFS=y >> $OUT_DIR/.config;
            make -C $KERNEL_DIR O=$OUT_DIR olddefconfig;
          "' >> $CONFIG_FILE
          cat $CONFIG_FILE

      - name: Fake prebuilts NDK
        run: |
          mkdir -p prebuilts/ndk
          echo "fake ndk ok"

      - name: 🛠️ Build Kernel (Auto Detect)
        run: |
          cd kernel-src/$KERNEL_DIR
          if [ -f "build.sh" ]; then
            bash build.sh
          else
            make ARCH=arm64 a06x_defconfig
            make ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          fi

      - name: Debug build tree
        run: |
          echo "📂 Kiểm tra dist/"
          ls -R kernel-src/$KERNEL_DIR/out/target/product/a06x/obj/KERNEL_OBJ/arch/arm64/boot || true
          ls -R kernel-src/$KERNEL_DIR/out/target/product/a06x/obj/KERNEL_OBJ/dist || true

      - name: Verify KernelSU & SUSFS in config
        run: |
          cd kernel-src/$KERNEL_DIR/out
          grep -q "CONFIG_KSU=y" .config && echo "✅ CONFIG_KSU đã bật" || (echo "❌ Chưa bật KSU"; exit 1)
          grep -q "CONFIG_SUSFS=y" .config && echo "✅ CONFIG_SUSFS đã bật" || (echo "❌ Chưa bật SUSFS"; exit 1)

      - name: Package AnyKernel3 (KernelSU + SUSFS)
        run: |
          set -eux
          DIST_DIR=kernel-src/$KERNEL_DIR/out/target/product/a06x/obj/KERNEL_OBJ/dist
          IMG=""
          if [ -f "$DIST_DIR/Image.gz" ]; then
            IMG=$DIST_DIR/Image.gz
          elif [ -f "$DIST_DIR/Image.lz4" ]; then
            IMG=$DIST_DIR/Image.lz4
          elif [ -f "$DIST_DIR/Image" ]; then
            IMG=$DIST_DIR/Image
          fi
          if [ -z "$IMG" ]; then
            echo "❌ Không tìm thấy kernel Image trong $DIST_DIR"
            exit 1
          fi
          cp "$IMG" AnyKernel3/Image
          cp -r $DIST_DIR/dtbo* AnyKernel3/ || true
          cd AnyKernel3
          zip -r9 "../Kernel-A06-5.15-KSU-SUSFS.zip" . -x .git README.md *.zip

      - name: Upload Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Zip
          path: Kernel-A06-5.15-KSU-SUSFS.zip

      - name: Upload Boot Outputs
        uses: actions/upload-artifact@v4
        with:
          name: Boot-Outputs
          path: kernel-src/$KERNEL_DIR/out/target/product/a06x/obj/KERNEL_OBJ/arch/arm64/boot/*

      - name: Upload Kernel Config
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Config
          path: kernel-src/$KERNEL_DIR/out/.config

      - name: Upload ABI Symbollist
        uses: actions/upload-artifact@v4
        with:
          name: ABI-Symbollist
          path: kernel-src/$KERNEL_DIR/out/abi_symbollist

      - name: Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: Build-Log
          path: kernel-src/$KERNEL_DIR/out/build.log

      - name: Save Original Kernel Tree
        run: |
          zip -r ../Kernel-A06-Original.zip kernel-src/$KERNEL_DIR

      - name: Generate Patch & Collect Rejects
        run: |
          cd kernel-src/$KERNEL_DIR
          git init
          git add .
          git commit -m "Original kernel source"
          git apply --reject ../../susfs/*.patch || true
          cd ../..
          git -C kernel-src/$KERNEL_DIR diff > Kernel-A06-KSU-SUSFS.patch
          zip -r Kernel-A06-Rejects.zip kernel-src/$KERNEL_DIR/*.rej || true

      - name: Upload Original, Patch, Rejects
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Patches
          path: |
            Kernel-A06-Original.zip
            Kernel-A06-KSU-SUSFS.patch
            Kernel-A06-Rejects.zip

      - name: Post Cache ccache
        run: |
          ccache -s
