name: Patch SUSFS into Samsung A06 5G Kernel

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 📥 Download Kernel Source (Samsung A06 5G)
        run: |
          wget -O kernel_src.zip https://github.com/huyzilo77-bot/Bufffkerrnela065g/releases/download/V1/A066B-5G.zip
          unzip kernel_src.zip
          tar -xvf Kernel.tar.gz
          ls -la

      - name: 📤 Upload Original Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel-original
          path: kernel-5.15

      - name: 📥 Clone SUSFS
        run: |
          git clone -b gki-android13-5.15 https://gitlab.com/simonpunk/susfs4ksu.git susfs

      - name: 🩹 Apply SUSFS patches
        run: |
          cd kernel-5.15
          for p in ../susfs/patches/*.patch; do
            echo "Applying $p"
            patch -p1 < "$p" || true
          done
          echo "✅ Done patching"

      - name: 📂 Collect .rej files
        if: always()
        run: |
          mkdir -p ../rej_out
          find . -name "*.rej" -exec cp --parents {} ../rej_out/ \; || true
        working-directory: kernel-5.15

      - name: 📤 Upload Patched Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel-patched-susfs
          path: kernel-5.15

      - name: 📤 Upload .rej (if any)
        uses: actions/upload-artifact@v4
        with:
          name: susfs-rejects
          path: rej_out
