name: Patch Kernel A06 with SUSFS

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workflow Repo
        uses: actions/checkout@v4

      - name: Download Kernel Source (Samsung A06 Release)
        run: |
          mkdir source && cd source
          wget -q https://github.com/huyzilo77-bot/Bufffkerrnela065g/releases/download/V1/SM-A066B_15_Opensource.zip
          unzip SM-A066B_15_Opensource.zip
          tar -xvf Kernel.tar.gz
          echo "✅ Giải nén xong kernel source"
          ls -la
          ls -la kernel-5.15 || true

      - name: Clone SUSFS
        run: |
          git clone -b gki-android13-5.15 https://gitlab.com/simonpunk/susfs4ksu.git susfs
          ls -la susfs || true

      - name: Patch Kernel with SUSFS
        run: |
          cd source/kernel-5.15
          echo "🔧 Áp dụng patch SUSFS..."
          patch -p1 < ../../susfs/ksu_susfs.patch || true
          echo "✅ Patch xong, kiểm tra file .rej nếu có"
          find . -name "*.rej" || true

      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts
          cp -r source/kernel-5.15 artifacts/kernel-5.15-patched || true
          cp -r source/kernel-5.15 artifacts/kernel-5.15-unpatched || true
          find source/kernel-5.15 -name "*.rej" -exec cp --parents {} artifacts/ \; || true

      - name: Upload Patched Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel-5.15-patched
          path: artifacts/kernel-5.15-patched

      - name: Upload Unpatched Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel-5.15-unpatched
          path: artifacts/kernel-5.15-unpatched

      - name: Upload Patch Rejects
        uses: actions/upload-artifact@v4
        with:
          name: susfs-rejects
          path: artifacts/**/*.rej
